#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use StaleFish\Application;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();

$application = new Application();
$application->run($input);